INSERT INTO `countries` (`countryId`, `country`, `currency`, `code`) VALUES
(1, 'Afghanistan', 'AFN', 'AF'),
(2, 'Albania', 'ALL', 'AL'),
(3, 'Algeria', 'DZD', 'DZ'),
(4, 'American Samoa', 'USD', 'AS'),
(5, 'Andorra', 'EUR', 'AD'),
(6, 'Angola', 'AOA', 'AO'),
(7, 'Anguilla', 'XCD', 'AI'),
(8, 'Antigua', 'XCD', 'AG'),
(9, 'Argentina', 'ARS', 'AR'),
(10, 'Armenia', 'AMD', 'AM'),
(11, 'Aruba', 'AWG', 'AW'),
(12, 'Australia', 'AUD', 'AU'),
(13, 'Austria', 'EUR', 'AT'),
(14, 'Azerbaijan', 'AZN', 'AZ'),
(15, 'Bahamas', 'BSD', 'BS'),
(16, 'Bahrain', 'BHD', 'BH'),
(17, 'Bangladesh', 'BDT', 'BD'),
(18, 'Barbados', 'BBD', 'BB'),
(19, 'Belarus', 'BYN', 'BY'),
(20, 'Belgium', 'EUR', 'BE'),
(21, 'Belize', 'BZD', 'BZ'),
(22, 'Benin', 'XOF', 'BJ'),
(23, 'Bermuda', 'BMD', 'BM'),
(24, 'Bhutan', 'BTN', 'BT'),
(25, 'Bolivia', 'BOB', 'BO'),
(26, 'Bosnia-Herzegovina', 'BAM', 'BA'),
(27, 'Botswana', 'BWP', 'BW'),
(28, 'Bouvet Island', 'NOK', 'BV'),
(29, 'Brazil', 'BRL', 'BR'),
(30, 'British Indian O Terr', 'GBP', 'IO'),
(31, 'British Virgin Islands', 'USD', 'VG'),
(32, 'Brunei Darussalam', 'BND', 'BN'),
(33, 'Bulgaria', 'BGN', 'BG'),
(34, 'Burkina Faso', 'XOF', 'BF'),
(35, 'Burundi', 'BIF', 'BI'),
(36, 'Cambodia', 'KHR', 'KH'),
(37, 'Cameroon', 'XAF', 'CM'),
(38, 'Canada', 'CAD', 'CA'),
(39, 'Cape Verde', 'CVE', 'CV'),
(40, 'Cayman Islands', 'KYD', 'KY'),
(41, 'Central African Rep.', 'XAF', 'CF'),
(42, 'Chad', 'XAF', 'TD'),
(43, 'Chile', 'CLP', 'CL'),
(44, 'China', 'CNY', 'CN'),
(45, 'Christmas Island', 'AUD', 'CX'),
(46, 'Cocos (Keeling) Islands', 'AUD', 'CC'),
(47, 'Colombia', 'COP', 'CO'),
(48, 'Comoros', 'KMF', 'KM'),
(49, 'Congo (Brazzaville)', 'XAF', 'CG'),
(50, 'Cook Islands', 'NZD', 'CK'),
(51, 'Costa Rica', 'CRC', 'CR'),
(52, 'Croatia', 'HRK', 'HR'),
(53, 'Cuba', 'CUC', 'CU'),
(54, 'Cyprus', 'EUR', 'CY'),
(55, 'Czech Republic', 'CZK', 'CS'),
(56, 'Democratic Republic of Congo (Kinshasa-Zaire)', 'CDF', 'CD'),
(57, 'Denmark', 'DKK', 'DK'),
(58, 'Djibouti', 'DJF', 'DJ'),
(59, 'Dominica', 'XCD', 'DM'),
(60, 'Dominican Republic', 'DOP', 'DO'),
(61, 'Ecuador', 'USD', 'EC'),
(62, 'Egypt', 'EGP', 'EG'),
(63, 'El Salvador', 'SVC', 'SV'),
(64, 'Eritrea', 'ERN', 'ER'),
(65, 'Estonia', 'EUR', 'EE'),
(66, 'Ethiopia', 'ETB', 'ET'),
(67, 'European Union', 'EUR', 'EU'),
(68, 'Falkland Isl Malvinas', 'FKP', 'FK'),
(69, 'Faroe Islands', 'DKK', 'FO'),
(70, 'Fiji', 'FJD', 'FJ'),
(71, 'Finland', 'EUR', 'FI'),
(72, 'France', 'EUR', 'FR'),
(73, 'France Metropolitan', 'EUR', 'FR'),
(74, 'French Guiana', 'EUR', 'GF'),
(75, 'French Polynesia', 'XPF', 'PF'),
(76, 'French Southern Terr', 'EUR', 'TF'),
(77, 'Gabon', 'XAF', 'GA'),
(78, 'Gambia', 'GMD', 'GM'),
(79, 'Georgia', 'GEL', 'GE'),
(80, 'Germany', 'EUR', 'DE'),
(81, 'Ghana', 'GHS', 'GH'),
(82, 'Gibraltar', 'GIP', 'GI'),
(83, 'Great Britain - UK', 'GBP', 'UK'),
(84, 'Greece', 'EUR', 'GR'),
(85, 'Greenland (Denmark)', 'DKK', 'GL'),
(86, 'Grenada', 'XCD', 'GD'),
(87, 'Guadaloupe', 'EUR', 'GP'),
(88, 'Guam (US)', 'USD', 'GU'),
(89, 'Guatemala', 'GTQ', 'GT'),
(90, 'Guernsey', 'GGP', 'GG'),
(91, 'Guinea (Conakry)', 'GNF', 'GN'),
(92, 'Guinea Bissau', 'XAF', 'GW'),
(93, 'Guyana', 'GYD', 'GY'),
(94, 'Haiti', 'HTG', 'HT'),
(95, 'Heard and McDonald Isl.', 'AUD', 'HM'),
(96, 'Honduras', 'HNL', 'HN'),
(97, 'Hong Kong', 'HKD', 'HK'),
(98, 'Hungary', 'HUF', 'HU'),
(99, 'Iceland', 'ISK', 'IS'),
(100, 'India', 'INR', 'IN'),
(101, 'Indonesia', 'IDR', 'ID'),
(102, 'Iran', 'IRR', 'IR'),
(103, 'Iraq', 'IQD', 'IQ'),
(104, 'Ireland', 'EUR', 'IE'),
(105, 'Isle of Man', 'IMP', 'IM'),
(106, 'Israel', 'ILS', 'IL'),
(107, 'Italy', 'EUR', 'IT'),
(108, 'Ivory Coast', 'XOF', 'CI'),
(109, 'Jamaica', 'JMD', 'JM'),
(110, 'Japan', 'JPY', 'JP'),
(111, 'Jersey', 'JEP', 'JE'),
(112, 'Jordan', 'JOD', 'JO'),
(113, 'Kazakhstan', 'KZT', 'KZ'),
(114, 'Kenya', 'KES', 'KE'),
(115, 'Kiribati', 'KID', 'KI'),
(116, 'Kuwait', 'KWD', 'KW'),
(117, 'Kyrgyz Republic', 'KGS', 'KG'),
(118, 'Laos', 'LAK', 'LA'),
(119, 'Latvia', 'EUR', 'LV'),
(120, 'Lebanon', 'LBP', 'LB'),
(121, 'Lesotho', 'LSL', 'LS'),
(122, 'Liberia', 'LRD', 'LR'),
(123, 'Libya', 'LYD', 'LY'),
(124, 'Liechtenstein', 'CHF', 'LI'),
(125, 'Lithuania', 'LTL', 'LT'),
(126, 'Luxembourg', 'EUR', 'LU'),
(127, 'Macau', 'MOP', 'MO'),
(128, 'Macedonia', 'MKD', 'MK'),
(129, 'Madagascar', 'MGA', 'MG'),
(130, 'Malawi', 'MWK', 'MW'),
(131, 'Malaysia', 'MYR', 'MY'),
(132, 'Maldives', 'MVR', 'MV'),
(133, 'Mali', 'XOF', 'ML'),
(134, 'Malta', 'EUR', 'MT'),
(135, 'Marshall Islands', 'USD', 'MH'),
(136, 'Martinique', 'EUR', 'MQ'),
(137, 'Mauritania', 'MRU', 'MR'),
(138, 'Mauritius', 'MUR', 'MU'),
(139, 'Mayotte', 'EUR', 'YT'),
(140, 'Mexico', 'MXN', 'MX'),
(141, 'Micronesia', 'USD', 'FM'),
(142, 'Moldova', 'MDL', 'MD'),
(143, 'Monaco', 'EUR', 'MC'),
(144, 'Mongolia', 'MNT', 'MN'),
(145, 'Montenegro', 'EUR', 'ME'),
(146, 'Montserrat', 'XCD', 'MS'),
(147, 'Morocco', 'MAD', 'MA'),
(148, 'Mozambique', 'MZN', 'MZ'),
(149, 'Myanmar', 'MMK', 'MM'),
(150, 'Namibia', 'NAD', 'nan'),
(151, 'Nauru', 'AUD', 'NR'),
(152, 'Nepal', 'NPR', 'NP'),
(153, 'Netherland Antilles', 'ANG', 'AN'),
(154, 'Netherlands', 'EUR', 'NL'),
(155, 'New Caledonia', 'XPF', 'NC'),
(156, 'New Zealand', 'NZD', 'NZ'),
(157, 'Nicaragua', 'NIO', 'NI'),
(158, 'Niger', 'XOF', 'NE'),
(159, 'Nigeria', 'NGN', 'NG'),
(160, 'Niue', 'NZD', 'NU'),
(161, 'Norfolk Island', 'AUD', 'NF'),
(162, 'North Korea', 'KPW', 'KP'),
(163, 'Northern Mariana Isl.', 'USD', 'MP'),
(164, 'Norway', 'NOK', 'NO'),
(165, 'Oman', 'OMR', 'OM'),
(166, 'Pakistan', 'PKR', 'PK'),
(167, 'Palau', 'USD', 'PW'),
(168, 'Palestine', 'ILS', 'PS'),
(169, 'Panama', 'PAB', 'PA'),
(170, 'Papua New Guinea', 'PGK', 'PG'),
(171, 'Paraguay', 'PYG', 'PY'),
(172, 'Peru', 'PEN', 'PE'),
(173, 'Philippines', 'PHP', 'PH'),
(174, 'Pitcairn', 'NZD', 'PN'),
(175, 'Poland', 'PLN', 'PL'),
(176, 'Portugal', 'EUR', 'PT'),
(177, 'Puerto Rico', 'USD', 'PR'),
(178, 'Qatar', 'QAR', 'QA'),
(179, 'Reunion', 'EUR', 'RE'),
(180, 'Romania', 'RON', 'RO'),
(181, 'Russian Federation', 'RUB', 'RU'),
(182, 'Rwanda', 'RWF', 'RW'),
(183, 'Saint Lucia', 'XCD', 'LC'),
(184, 'Saint Pierre and Miquelon', 'EUR', 'PM'),
(185, 'San Marino', 'EUR', 'SM'),
(186, 'Saudi Arabia', 'SAR', 'SA'),
(187, 'Senegal', 'XOF', 'SN'),
(188, 'Serbia', 'RSD', 'RS'),
(189, 'Seychelles', 'SCR', 'SC'),
(190, 'Sierra Leone', 'SLL', 'SL'),
(191, 'Singapore', 'SGD', 'SG'),
(192, 'Sint Maarten (Dutch part)', 'ANG', 'SX'),
(193, 'Slovakia', 'EUR', 'SK'),
(194, 'Slovenia', 'EUR', 'SI'),
(195, 'Solomon Islands', 'SBD', 'SB'),
(196, 'Somalia', 'SOS', 'SO'),
(197, 'South Africa', 'ZAR', 'ZA'),
(198, 'South Georgia and South Sandwich Islands', 'GBP', 'GS'),
(199, 'South Korea', 'KRW', 'KR'),
(200, 'South Sudan', 'SSP', 'SS'),
(201, 'Soviet Union', 'RUB', 'RU'),
(202, 'Spain', 'EUR', 'ES'),
(203, 'Sri Lanka', 'LKR', 'LK'),
(204, 'St. Helena', 'SHP', 'SH'),
(205, 'St. Tome and Principe', 'STN', 'ST'),
(206, 'St.Kitts Nevis Anguilla', 'XCD', 'KN'),
(207, 'St.Vincent and Grenadines', 'XCD', 'VC'),
(208, 'Sudan', 'SDG', 'SD'),
(209, 'Suriname', 'SRD', 'SR'),
(210, 'Svalbard and Jan Mayen Is', 'NOK', 'SJ'),
(211, 'Swaziland', 'SZL', 'SZ'),
(212, 'Sweden', 'SEK', 'SE'),
(213, 'Switzerland', 'CHF', 'CH'),
(214, 'Syria', 'SYP', 'SY'),
(215, 'Taiwan', 'TWD', 'TW'),
(216, 'Tajikistan', 'TJS', 'TJ'),
(217, 'Tanzania', 'TZS', 'TZ'),
(218, 'Thailand', 'THB', 'TH'),
(219, 'Timor-Leste', 'USD', 'TL'),
(220, 'Togo', 'XOF', 'TG'),
(221, 'Tokelau', 'NZD', 'TK'),
(222, 'Tonga', 'TOP', 'TO'),
(223, 'Trinidad and Tobago', 'TTD', 'TT'),
(224, 'Tunisia', 'TND', 'TN'),
(225, 'Turkey', 'TRY', 'TR'),
(226, 'Turkmenistan', 'TMT', 'TM'),
(227, 'Turks and Caicos Islands', 'USD', 'TC'),
(228, 'Tuvalu', 'AUD', 'TV'),
(229, 'Uganda', 'UGX', 'UG'),
(230, 'Ukraine', 'UAH', 'UA'),
(231, 'United Arab Emirates', 'AED', 'AE'),
(232, 'United States', 'USD', 'US'),
(233, 'Uruguay', 'UYU', 'UY'),
(234, 'US Minor outlying Isl.', 'USD', 'UM'),
(235, 'US Virgin Islands', 'USD', 'VI'),
(236, 'Uzbekistan', 'UZS', 'UZ'),
(237, 'Vanuatu', 'VUV', 'VU'),
(238, 'Vatican City State', 'EUR', 'VA'),
(239, 'Venezuela', 'VES', 'VE'),
(240, 'Vietnam', 'VND', 'VN'),
(241, 'Wallis and Futuna Islands', 'XPF', 'WF'),
(242, 'Western Sahara', 'MAD', 'EH'),
(243, 'Western Samoa', 'WST', 'WS'),
(244, 'Yemen', 'YER', 'YE'),
(245, 'Yugoslavia', 'YUN', 'YU'),
(246, 'Zambia', 'ZMW', 'ZM'),
(247, 'Zimbabwe', 'ZWL', 'ZW');
